import { useMutation, useQuery } from 'convex/react'
import { makeFunctionReference } from 'convex/server'
import { useEffect, useMemo, useState, type ReactElement } from 'react'

import type { Doc, Id } from '../../convex/_generated/dataModel'

type Workflow = 'chat' | 'daily' | 'session'
type Runtime = { workflow: Workflow; modelId: string; systemPrompt: string; poolIds: Id<'debugLiveGeminiPools'>[]; cacheEnabled: boolean; cacheTtlSeconds: number; source: 'default' | 'published'; configId?: string }
type Dashboard = { error: string | null; defaults: Runtime[]; states: Doc<'debugLiveGeminiState'>[]; configs: Doc<'debugLiveGeminiConfigs'>[]; activations: Doc<'debugLiveGeminiActivations'>[]; pools: Array<Doc<'debugLiveGeminiPools'> & { keyAvailable: boolean }>; limits: Doc<'debugLiveGeminiQuotaLimits'>[]; caches: Doc<'debugLiveGeminiCaches'>[]; keyAliases: string[] }
const dashboardQuery = makeFunctionReference<'query', Record<string, never>, Dashboard>('debug/liveGemini:dashboard')
const saveDraft = makeFunctionReference<'mutation', { configId?: Id<'debugLiveGeminiConfigs'>; workflow: Workflow; name: string; modelId: string; systemPrompt: string; poolIds: Id<'debugLiveGeminiPools'>[]; cacheEnabled: boolean; cacheTtlSeconds: number }, { configId?: Id<'debugLiveGeminiConfigs'>; error?: string }>('debug/liveGemini:saveDraft')
const publish = makeFunctionReference<'mutation', { configId: Id<'debugLiveGeminiConfigs'>; confirmation: 'PUBLISH LIVE CONFIG' }, { ok?: boolean; error?: string }>('debug/liveGemini:publishDraft')
const activate = makeFunctionReference<'mutation', { configId: Id<'debugLiveGeminiConfigs'>; confirmation: 'ROLL BACK LIVE CONFIG' }, { ok?: boolean; error?: string }>('debug/liveGemini:activatePublished')
const savePool = makeFunctionReference<'mutation', { poolId?: Id<'debugLiveGeminiPools'>; name: string; keyAlias: string; resetTimezone: string; enabled: boolean; modelId: string; rpm: number; rpd: number; tpm?: number }, { poolId?: Id<'debugLiveGeminiPools'>; error?: string }>('debug/liveGemini:savePool')
const backfillLegacy = makeFunctionReference<'mutation', Record<string, never>, { updated?: number; error?: string }>('debug/liveGemini:backfillLegacyRecords')
const workflowName: Record<Workflow, string> = { chat: 'Main chat', daily: 'Daily summaries', session: 'Session summaries' }
function stamp(value: number | undefined): string { return value === undefined ? 'Not published' : new Date(value).toLocaleString() }

function WorkflowEditor({ workflow, data, notice }: { workflow: Workflow; data: Dashboard; notice: (value: string) => void }): ReactElement {
  const save = useMutation(saveDraft); const publishDraft = useMutation(publish); const activatePublished = useMutation(activate)
  const active = useMemo(() => { const state = data.states.find((item) => item.workflow === workflow); return data.configs.find((item) => item._id === state?.activeConfigId) ?? data.defaults.find((item) => item.workflow === workflow)! }, [data, workflow])
  const [draftId, setDraftId] = useState<Id<'debugLiveGeminiConfigs'> | undefined>(); const [name, setName] = useState(`${workflowName[workflow]} draft`); const [modelId, setModelId] = useState(''); const [prompt, setPrompt] = useState(''); const [poolIds, setPoolIds] = useState<Id<'debugLiveGeminiPools'>[]>([]); const [cacheEnabled, setCacheEnabled] = useState(false); const [ttl, setTtl] = useState(3600)
  useEffect(() => { if (!modelId && !prompt) { setModelId(active.modelId); setPrompt(active.systemPrompt); setPoolIds(active.poolIds ?? []); setCacheEnabled(active.cacheEnabled ?? false); setTtl(active.cacheTtlSeconds ?? 3600) } }, [active, modelId, prompt])
  const saveCurrent = async (): Promise<Id<'debugLiveGeminiConfigs'> | undefined> => { const result = await save({ configId: draftId, workflow, name, modelId, systemPrompt: prompt, poolIds, cacheEnabled, cacheTtlSeconds: ttl }); if (result.error !== undefined) { notice(result.error); return undefined }; setDraftId(result.configId); notice('Draft saved.'); return result.configId }
  const published = data.configs.filter((item) => item.workflow === workflow && item.status === 'published')
  const activeIsDefault = 'source' in active && active.source === 'default'; const activeId = '_id' in active ? active._id : active.configId
  return <section className="live-gemini-editor"><p className="section-kicker">{workflowName[workflow].toUpperCase()}</p><h2>{active.modelId}</h2><p>{activeIsDefault ? 'Code default is active.' : 'Published live configuration is active.'} Explicit caching only stores this workflow’s immutable prompt (and fixed chat tools), never user context.</p><label>Name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Model ID<input value={modelId} onChange={(event) => setModelId(event.target.value)} /></label><label>System prompt<textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} /></label><fieldset><legend>Key pools</legend>{data.pools.map((pool) => <label key={pool._id}><input type="checkbox" checked={poolIds.includes(pool._id)} onChange={(event) => setPoolIds(event.target.checked ? [...poolIds, pool._id] : poolIds.filter((id) => id !== pool._id))} /> {pool.name} {!pool.keyAvailable ? '(key unavailable)' : ''}</label>)}</fieldset><label><input type="checkbox" checked={cacheEnabled} onChange={(event) => setCacheEnabled(event.target.checked)} /> Enable explicit Gemini cache</label><label>Cache TTL (seconds)<input min="60" max="86400" type="number" value={ttl} onChange={(event) => setTtl(Number(event.target.value))} /></label><div className="header-actions"><button className="quiet-button" onClick={() => void saveCurrent()} type="button">Save draft</button><button className="primary-button" onClick={() => void saveCurrent().then(async (id) => { if (id !== undefined && window.prompt('Type PUBLISH LIVE CONFIG to activate this version.') === 'PUBLISH LIVE CONFIG') { const result = await publishDraft({ configId: id, confirmation: 'PUBLISH LIVE CONFIG' }); notice(result.error ?? 'Published.') } })} type="button">Publish</button></div><div className="live-gemini-history">{published.map((config) => <article key={config._id}><div><strong>{config.name}</strong><span>{config.modelId} · {stamp(config.publishedAt)}</span></div>{activeId === config._id ? <small>Active</small> : <button className="quiet-button" onClick={() => { if (window.prompt('Type ROLL BACK LIVE CONFIG to activate this version.') === 'ROLL BACK LIVE CONFIG') void activatePublished({ configId: config._id, confirmation: 'ROLL BACK LIVE CONFIG' }).then((result) => notice(result.error ?? 'Version activated.')) }} type="button">Roll back</button>}</article>)}</div></section>
}

export function LiveGemini({ onBack }: { onBack: () => void }): ReactElement {
  const data = useQuery(dashboardQuery, {}); const save = useMutation(savePool); const backfill = useMutation(backfillLegacy); const [notice, setNotice] = useState<string | null>(null); const [editingPoolId, setEditingPoolId] = useState<Id<'debugLiveGeminiPools'> | undefined>(); const [poolName, setPoolName] = useState(''); const [keyAlias, setKeyAlias] = useState(''); const [poolEnabled, setPoolEnabled] = useState(true); const [model, setModel] = useState('gemini-3.6-flash'); const [rpm, setRpm] = useState(10); const [rpd, setRpd] = useState(100); const [tpm, setTpm] = useState('')
  if (data === undefined) return <main className="console-shell"><div className="console-loading">Reading live Gemini controls…</div></main>
  if (data.error !== null) return <main className="console-shell"><section className="disabled-panel"><p>{data.error}</p></section></main>
  const editPool = (pool: Dashboard['pools'][number]): void => { const limit = data.limits.find((item) => item.poolId === pool._id && item.modelId === model) ?? data.limits.find((item) => item.poolId === pool._id); setEditingPoolId(pool._id); setPoolName(pool.name); setKeyAlias(pool.keyAlias); setPoolEnabled(pool.enabled); setModel(limit?.modelId ?? model); setRpm(limit?.rpm ?? 10); setRpd(limit?.rpd ?? 100); setTpm(limit?.tpm === undefined ? '' : String(limit.tpm)) }
  const clearPool = (): void => { setEditingPoolId(undefined); setPoolName(''); setKeyAlias(''); setPoolEnabled(true); setModel('gemini-3.6-flash'); setRpm(10); setRpd(100); setTpm('') }
  const saveCurrentPool = (): void => { void save({ poolId: editingPoolId, name: poolName, keyAlias, resetTimezone: 'America/Los_Angeles', enabled: poolEnabled, modelId: model, rpm, rpd, tpm: tpm ? Number(tpm) : undefined }).then((result) => { setNotice(result.error ?? 'Pool saved.'); if (result.poolId !== undefined) setEditingPoolId(result.poolId) }) }
  return <main className="console-shell"><header className="console-header"><div className="brand-lockup"><span className="brand-mark">E</span><div><p className="eyebrow">DEVELOPMENT ONLY</p><h1>Live Gemini Controls</h1></div></div><div className="header-actions"><button className="quiet-button" onClick={() => void backfill({}).then((result) => setNotice(result.error ?? `Updated ${result.updated ?? 0} legacy records.`))} type="button">Backfill legacy controls</button><button className="text-button" onClick={onBack} type="button">Debug console</button></div></header><section className="live-gemini-active"><p className="section-kicker">TRAFFIC POOLS</p><h2>{editingPoolId === undefined ? 'New pool' : 'Edit pool'}</h2><p>Main chat tries assigned pools in order and falls through to the next key when the first pool cannot admit a new turn.</p><label>Pool name<input value={poolName} onChange={(event) => setPoolName(event.target.value)} /></label><label>Key alias<select value={keyAlias} onChange={(event) => setKeyAlias(event.target.value)}><option value="">Choose configured alias</option>{data.keyAliases.map((alias) => <option key={alias}>{alias}</option>)}</select></label><label>Model<input value={model} onChange={(event) => setModel(event.target.value)} /></label><label>RPM<input type="number" value={rpm} onChange={(event) => setRpm(Number(event.target.value))} /></label><label>RPD<input type="number" value={rpd} onChange={(event) => setRpd(Number(event.target.value))} /></label><label>TPM (optional)<input value={tpm} onChange={(event) => setTpm(event.target.value)} /></label><label><input type="checkbox" checked={poolEnabled} onChange={(event) => setPoolEnabled(event.target.checked)} /> Enabled</label><div className="header-actions"><button className="quiet-button" onClick={clearPool} type="button">New pool</button><button className="quiet-button" onClick={saveCurrentPool} type="button">{editingPoolId === undefined ? 'Save pool' : 'Update pool'}</button></div><div className="evaluation-list">{data.pools.map((pool) => <div key={pool._id}><div><strong>{pool.name}</strong><span>{pool.keyAlias} · {pool.enabled ? 'enabled' : 'disabled'} · {pool.keyAvailable ? 'key available' : 'key unavailable'}</span></div><button className="quiet-button" onClick={() => editPool(pool)} type="button">Edit</button></div>)}</div></section>{(['chat', 'daily', 'session'] as const).map((workflow) => <WorkflowEditor key={workflow} workflow={workflow} data={data} notice={setNotice} />)}{notice === null ? null : <p className="evaluation-notice">{notice}</p>}</main>
}
