import { defineTable } from 'convex/server'
import { v } from 'convex/values'

export const debugTables = {
  debugConsoleApprovals: defineTable({
    authUserId: v.id('users'),
    approvedAt: v.number(),
  }).index('by_authUserId', ['authUserId']),
  debugTurnEvents: defineTable({
    userId: v.id('profiles'),
    chatId: v.id('chats'),
    messageId: v.id('messages'),
    runId: v.string(),
    sequence: v.number(),
    kind: v.union(
      v.literal('lifecycle'),
      v.literal('context'),
      v.literal('gemini'),
      v.literal('tool'),
      v.literal('validation'),
      v.literal('database'),
      v.literal('error'),
      v.literal('warning'),
    ),
    status: v.union(
      v.literal('info'),
      v.literal('running'),
      v.literal('success'),
      v.literal('warning'),
      v.literal('error'),
      v.literal('skipped'),
    ),
    title: v.string(),
    summary: v.optional(v.string()),
    source: v.object({
      file: v.string(),
      symbol: v.string(),
    }),
    details: v.optional(v.string()),
    callIndex: v.optional(v.number()),
    toolName: v.optional(v.string()),
    durationMs: v.optional(v.number()),
    tokens: v.optional(
      v.object({
        prompt: v.optional(v.number()),
        output: v.optional(v.number()),
        total: v.number(),
      }),
    ),
    warningCodes: v.array(v.string()),
    occurredAt: v.number(),
    createdAt: v.number(),
  })
    .index('by_message_and_sequence', ['messageId', 'sequence'])
    .index('by_user_and_createdAt', ['userId', 'createdAt']),
  debugReplaySnapshots: defineTable({
    userId: v.id('profiles'),
    messageId: v.id('messages'),
    runId: v.string(),
    payload: v.string(),
    capturedAt: v.number(),
  })
    .index('by_message', ['messageId'])
    .index('by_user_and_capturedAt', ['userId', 'capturedAt']),
  debugReplayExperiments: defineTable({
    userId: v.id('profiles'),
    messageId: v.id('messages'),
    status: v.union(v.literal('running'), v.literal('completed'), v.literal('failed')),
    snapshotSource: v.union(v.literal('captured'), v.literal('reconstructed')),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
    error: v.optional(v.string()),
    critique: v.optional(v.string()),
    critiqueTokens: v.optional(v.number()),
  })
    .index('by_message_and_createdAt', ['messageId', 'createdAt'])
    .index('by_user_and_createdAt', ['userId', 'createdAt']),
  debugReplayResults: defineTable({
    experimentId: v.id('debugReplayExperiments'),
    variant: v.string(),
    sampleIndex: v.number(),
    rawText: v.string(),
    finalText: v.string(),
    functionCalls: v.string(),
    getDataSelected: v.boolean(),
    requestedFields: v.array(v.string()),
    promptTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    totalTokens: v.number(),
    durationMs: v.number(),
    error: v.optional(v.string()),
  }).index('by_experiment_and_variant', ['experimentId', 'variant']),
  // Development-only live Gemini controls. Published versions are immutable;
  // the singleton state selects the version used by new chat turns.
  debugLiveGeminiConfigs: defineTable({
    workflow: v.optional(v.union(v.literal('chat'), v.literal('daily'), v.literal('session'))),
    name: v.string(),
    modelId: v.string(),
    systemPrompt: v.string(),
    poolIds: v.optional(v.array(v.id('debugLiveGeminiPools'))),
    cacheEnabled: v.optional(v.boolean()),
    cacheTtlSeconds: v.optional(v.number()),
    status: v.union(v.literal('draft'), v.literal('published')),
    createdBy: v.id('users'),
    createdAt: v.number(),
    updatedAt: v.number(),
    publishedAt: v.optional(v.number()),
  }).index('by_workflow_and_status_and_createdAt', ['workflow', 'status', 'createdAt']),
  debugLiveGeminiState: defineTable({
    workflow: v.optional(v.union(v.literal('chat'), v.literal('daily'), v.literal('session'))),
    activeConfigId: v.id('debugLiveGeminiConfigs'),
    activatedBy: v.id('users'),
    activatedAt: v.number(),
  }).index('by_workflow', ['workflow']),
  debugLiveGeminiActivations: defineTable({
    workflow: v.optional(v.union(v.literal('chat'), v.literal('daily'), v.literal('session'))),
    configId: v.id('debugLiveGeminiConfigs'),
    activatedBy: v.id('users'),
    activatedAt: v.number(),
  }).index('by_workflow_and_activatedAt', ['workflow', 'activatedAt']),
  debugLiveGeminiPools: defineTable({
    name: v.string(),
    keyAlias: v.string(),
    resetTimezone: v.string(),
    enabled: v.boolean(),
    createdBy: v.id('users'),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_enabled_and_updatedAt', ['enabled', 'updatedAt']),
  debugLiveGeminiQuotaLimits: defineTable({
    poolId: v.id('debugLiveGeminiPools'),
    modelId: v.string(),
    rpm: v.number(),
    rpd: v.number(),
    tpm: v.optional(v.number()),
    updatedAt: v.number(),
  }).index('by_pool_and_model', ['poolId', 'modelId']),
  debugLiveGeminiReservations: defineTable({
    workflow: v.union(v.literal('chat'), v.literal('daily'), v.literal('session')),
    poolId: v.id('debugLiveGeminiPools'),
    modelId: v.string(),
    reservedRequests: v.number(),
    usedRequests: v.number(),
    totalTokens: v.number(),
    requestedAt: v.number(),
    dayKey: v.string(),
    status: v.union(v.literal('active'), v.literal('released')),
  }).index('by_pool_model_and_requestedAt', ['poolId', 'modelId', 'requestedAt'])
    .index('by_pool_model_day', ['poolId', 'modelId', 'dayKey']),
  debugLiveGeminiCaches: defineTable({
    configId: v.id('debugLiveGeminiConfigs'),
    cacheName: v.string(),
    expiresAt: v.number(),
    cachedTokens: v.optional(v.number()),
    lastError: v.optional(v.string()),
    updatedAt: v.number(),
  }).index('by_config', ['configId']),
  // Model-evaluation records are deliberately disconnected from profiles,
  // chats, messages, cards, and apiUsage. They contain synthetic fixtures only.
  debugEvaluationPrompts: defineTable({
    name: v.string(),
    content: v.string(),
    status: v.union(v.literal('draft'), v.literal('published'), v.literal('archived')),
    createdBy: v.id('users'),
    createdAt: v.number(),
    publishedAt: v.optional(v.number()),
  }).index('by_status_and_createdAt', ['status', 'createdAt']),
  debugEvaluationQuotaPools: defineTable({
    name: v.string(),
    keyAlias: v.string(),
    resetTimezone: v.string(),
    enabled: v.boolean(),
    createdBy: v.id('users'),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_enabled_and_updatedAt', ['enabled', 'updatedAt']),
  debugEvaluationQuotaLimits: defineTable({
    poolId: v.id('debugEvaluationQuotaPools'),
    modelId: v.string(),
    rpm: v.number(),
    rpd: v.number(),
    tpm: v.optional(v.number()),
    updatedAt: v.number(),
  }).index('by_pool_and_model', ['poolId', 'modelId']),
  debugEvaluationModelProfiles: defineTable({
    name: v.string(),
    modelId: v.string(),
    thinkingLevel: v.optional(v.string()),
    promptId: v.id('debugEvaluationPrompts'),
    poolIds: v.array(v.id('debugEvaluationQuotaPools')),
    inputPricePerMillion: v.number(),
    outputPricePerMillion: v.number(),
    enabled: v.boolean(),
    createdBy: v.id('users'),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_enabled_and_updatedAt', ['enabled', 'updatedAt']),
  debugEvaluationSuites: defineTable({
    name: v.string(),
    definitionJson: v.string(),
    status: v.union(v.literal('draft'), v.literal('published'), v.literal('archived')),
    createdBy: v.id('users'),
    createdAt: v.number(),
    publishedAt: v.optional(v.number()),
  }).index('by_status_and_createdAt', ['status', 'createdAt']),
  debugEvaluationExperiments: defineTable({
    name: v.string(),
    suiteSnapshotJson: v.string(),
    status: v.union(v.literal('draft'), v.literal('queued'), v.literal('running'), v.literal('paused'), v.literal('completed'), v.literal('cancelled')),
    blinded: v.boolean(),
    unblindedAt: v.optional(v.number()),
    createdBy: v.id('users'),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_status_and_updatedAt', ['status', 'updatedAt']),
  debugEvaluationArms: defineTable({
    experimentId: v.id('debugEvaluationExperiments'),
    armCode: v.string(),
    profileSnapshotJson: v.string(),
    expectedRequests: v.number(),
    worstCaseRequests: v.number(),
    createdAt: v.number(),
  }).index('by_experiment_and_armCode', ['experimentId', 'armCode']),
  // The sole allowed mutable experiment input: an admin may add a separate
  // project quota pool to a paused/queued experiment. Every change is audited.
  debugEvaluationPoolChanges: defineTable({
    experimentId: v.id('debugEvaluationExperiments'),
    armId: v.id('debugEvaluationArms'),
    poolId: v.id('debugEvaluationQuotaPools'),
    addedBy: v.id('users'),
    addedAt: v.number(),
  })
    .index('by_experiment_and_addedAt', ['experimentId', 'addedAt'])
    .index('by_arm_and_pool', ['armId', 'poolId']),
  debugEvaluationSamples: defineTable({
    experimentId: v.id('debugEvaluationExperiments'),
    armId: v.id('debugEvaluationArms'),
    caseId: v.string(),
    sampleIndex: v.number(),
    fixtureJson: v.string(),
    status: v.union(v.literal('queued'), v.literal('running'), v.literal('completed'), v.literal('incomplete'), v.literal('cancelled')),
    poolId: v.optional(v.id('debugEvaluationQuotaPools')),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_experiment_and_status', ['experimentId', 'status'])
    .index('by_arm_and_case', ['armId', 'caseId']),
  debugEvaluationAttempts: defineTable({
    sampleId: v.id('debugEvaluationSamples'),
    poolId: v.id('debugEvaluationQuotaPools'),
    status: v.union(v.literal('running'), v.literal('completed'), v.literal('incomplete')),
    finalReply: v.optional(v.string()),
    rawFinalReply: v.optional(v.string()),
    toolRoutingPassed: v.boolean(),
    hardFailureCodes: v.array(v.string()),
    promptTokens: v.number(),
    outputTokens: v.number(),
    totalTokens: v.number(),
    durationMs: v.number(),
    error: v.optional(v.string()),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index('by_sample_and_createdAt', ['sampleId', 'createdAt']),
  debugEvaluationCallSteps: defineTable({
    attemptId: v.id('debugEvaluationAttempts'),
    requestIndex: v.number(),
    functionCallsJson: v.string(),
    stubResultsJson: v.optional(v.string()),
    promptTokens: v.number(),
    outputTokens: v.number(),
    totalTokens: v.number(),
    durationMs: v.number(),
    createdAt: v.number(),
  }).index('by_attempt_and_requestIndex', ['attemptId', 'requestIndex']),
  debugEvaluationRequests: defineTable({
    poolId: v.id('debugEvaluationQuotaPools'),
    modelId: v.string(),
    attemptId: v.id('debugEvaluationAttempts'),
    requestedAt: v.number(),
    dayKey: v.string(),
  })
    .index('by_pool_model_and_requestedAt', ['poolId', 'modelId', 'requestedAt'])
    .index('by_pool_model_day', ['poolId', 'modelId', 'dayKey'])
    .index('by_attempt', ['attemptId']),
  debugEvaluationReviews: defineTable({
    sampleId: v.id('debugEvaluationSamples'),
    personaPassed: v.boolean(),
    safetyPassed: v.boolean(),
    hardFailure: v.boolean(),
    notes: v.string(),
    reviewedBy: v.id('users'),
    reviewedAt: v.number(),
  }).index('by_sample', ['sampleId']),
}
